import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Time from '@/components/Time'
import Weather from '@/components/Weather'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <header>
          <link href="https://fonts.googleapis.com/css2?family=Alike&family=DM+Sans:opsz,wght@9..40,100;9..40,200;9..40,300;9..40,400;9..40,500;9..40,600;9..40,700;9..40,800&family=Noto+Sans:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet" />
      </header>
      <body className={inter.className}>
        <Weather></Weather>
      </body>
    </html>
  )
}
